// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB9vyjqCCYaOM_BxMY9y-xiZmH3WapEY4',
    appId: '1:922905908291:web:5641f2e95f5887455cb0f6',
    messagingSenderId: '922905908291',
    projectId: 'investorconnect-8bdc1',
    authDomain: 'investorconnect-8bdc1.firebaseapp.com',
    storageBucket: 'investorconnect-8bdc1.appspot.com',
    measurementId: 'G-SX10NXW55B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvcc6Kke_PpfvSsp4g1bCk1KJFW_uobtM',
    appId: '1:922905908291:android:5cf109f4e120d7975cb0f6',
    messagingSenderId: '922905908291',
    projectId: 'investorconnect-8bdc1',
    storageBucket: 'investorconnect-8bdc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRbRJyJr1WEqc_HLEBEf_y4yx27ghaZA',
    appId: '1:922905908291:ios:67208ce266f61a5b5cb0f6',
    messagingSenderId: '922905908291',
    projectId: 'investorconnect-8bdc1',
    storageBucket: 'investorconnect-8bdc1.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgRbRJyJr1WEqc_HLEBEf_y4yx27ghaZA',
    appId: '1:922905908291:ios:0f4e787f20ee47915cb0f6',
    messagingSenderId: '922905908291',
    projectId: 'investorconnect-8bdc1',
    storageBucket: 'investorconnect-8bdc1.appspot.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}
